CREATE TABLE IF NOT EXISTS users (

    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin','user') NOT NULL DEFAULT 'user',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY uq_users_email (email)
);
ALTER TABLE users ADD COLUMN avatar VARCHAR(255) NULL AFTER role;

CREATE TABLE IF NOT EXISTS password_resets (

    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(150)  NOT NULL,
    otp_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_password_reset_email (email)
);

CREATE TABLE IF NOT EXISTS snippets (

    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code LONGTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);

ALTER TABLE snippets ADD COLUMN slug VARCHAR(60) NULL AFTER code;
ALTER TABLE snippets ADD UNIQUE KEY uq_snippets_slug (slug);
ALTER TABLE snippets ADD COLUMN user_id BIGINT UNSIGNED NULL AFTER id;
ALTER TABLE snippets ADD INDEX idx_snippets_user_id (user_id);